name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: 23.2
            elixir: 1.11.2
          - erlang: 22.2.1
            elixir: 1.9.4

    steps:
      - uses: actions/checkout@v1

      - name: Setup
        run: |
          make docker-setup DOCKER_OTP_VERSION=${{matrix.erlang}} DOCKER_ELIXIR_VERSION=${{matrix.elixir}}

      - name: Test
        run: |
          make docker-test DOCKER_OTP_VERSION=${{matrix.erlang}} DOCKER_ELIXIR_VERSION=${{matrix.elixir}}
